# GameOfWar Service definitions
services:
    logger:
        class: GameOfWar\Service\Logger
        arguments:
            - %appDir%/logs

    dealer:
        class: GameOfWar\Service\Dealer
        arguments:
            - @entity_manager
            - @logger

    game_manager:
        class: GameOfWar\Service\GameManager
        arguments:
            - @service_container

    umpire:
        class: GameOfWar\Service\Umpire
        arguments:
            - @entity_manager
            - @logger
