services:
    logger:
        class: GameOfWar\Service\Logger
        arguments:
            - %appDir%/logs

    dealer:
        class: GameOfWar\Service\Dealer
        arguments:
            - @service_container

    game_manager:
        class: GameOfWar\Service\GameManager
        arguments:
            - @service_container
            - @dealer

    umpire:
        class: GameOfWar\Service\Umpire
        arguments:
            - @service_container
